### ISSUE TITLE
Easy exposure of python functions

### ISSUE THREAD

**Issue by ajCameron** [mewbotorg/mewbot#46]
I've been thinking about how to elegantly expose python function directly to a bot - something similar to the discord.py decorator system. But YAML based.

Being more familiar with them, I've prototyped something with decorators.

(The example file with the decorator logic can be found [here](https://github.com/mewler/mewbot/blob/decorator_command_builder/examples/discord_params_command_builder.py). The  YAML to mke it work is fairly simple, but can be found [here](https://github.com/mewler/mewbot/blob/decorator_command_builder/examples/discord_params_command_builder.yaml).)

There are a couple of things I wanted to present for comment before implementing.

### Firstly - The current, decorator based constructor I have “working” - which has served as a testbed

I have written a constructor which uses decorators to register functions. It can then be called, at the end, to produce a combined trigger and action for these functions.

Functions can have (eventually) arbitrary pythonic signatures. But (currently) must return a single string.

The flow for the constructor is as follows
Either use override name of command, or name the command after the function - this will serve as the invocation command
Introspect the functional signature to construct a parser - this will be used to turn message text into args and kwargs to feed to the function.
Based on the combined names of all the functions, construct a trigger
Based on the combined functions, construct an action

### Secondly, my ideas for configuring this via YAML. Wanted to run it past people before implementing.

I propose the creation of a new ComponentKind - called something like BehaviorFunctionGroup.

It would hold a collection of functions and produce a Trigger and Action for them.

Configured with a YAML schema something like the below.

```
kind: BehaviorFunctionGroup
implementation: mewbot.api.v1.BehaviorFunctionGroup
uuid: aaaaaaaa-aaaa-4aaa-0000-aaaaaaaaaa01

properties:
  name: 'Expose a collection of functions'
  input: mewbot.io.discord.DiscordInputEvent
  input_adaptor: mewbot.io.discord.DiscordInputEventToTextAdaptor
  output: mewbot.io.discord.DiscordOutputEvent
  output_adaptor: mewbot.io.discord.TextToDiscordOutputEventAdaptor
  error_handler: mewbot.io.discord.ExceptionToDiscordOutputEventAdaptor

functions:
  - implementation: examples.python_function_to_discord.one_arg_function
    uuid: aaaaaaaa-aaaa-4aaa-0000-aaaaaaaaaa02
    properties: {}
  - implementation: examples.python_function_to_discord.two_arg_function
    uuid: aaaaaaaa-aaaa-4aaa-0000-aaaaaaaaaa03
    properties:
      name: “function_with_two_args”
      parser: mewbot.utils.parsers.PythonLikeParser
      error_handling: “print_only”

```

 E.t.c.

Under the BehaviorFunctionGroup the properties are as follows

input - The class of input event the BehaviorFunctionGroup
input_adaptor - Responsible for turning an input event into a string - which will then be parsed to the function parser

output - The output class the BehaviorFunctionGroup emits
output_adaptor - Responsible for turning the output of a function into an OutputEvent to go on the wire.

error_handler - Called with the exception and the error handling mode - which is defined on a function by function basis - if an error occurs when trying to run the function. Has access to the output queue, so it can emit a bot error message

Under the functions

implementation - the importable location of the function to expose

Under the function properties

nane - An override name of the function, if we’re not supposed to just use its existing name
parser - The parser which will be used to convert a string - produced by the input_adaptor - into a set of args and kwargs which will be used to call the function itself.
error_handling - Passed along with the exception into the error_handler to respond to the exception.

Can anyone think of a better way to implement this?

### Thirdly

I would like to work (an upgraded version of) the decorator logic from the example directly into mewbot - on the basis that it may be useful in the backend.

As a general philosophical point, I would like to consider levels and types of access for mewbot. The first thing supported should, of course, be YAML, but I think we should consider tools and methods to support easier use of mewbot in other projects.

If nothing else, it would be cool to allow easier porting of other projects to our framework. So I’d like to give thought to extending mewbot with additional tools to make coding bots purely in python easier.

In particular, I’d like to clone the interface for some of the popular bot frameworks, so bots written using those frameworks can be easily ported into ours. If not with no modification, then with minimal modification.

Possibly an extension of the api? Or a new top level called “emulation” - from which you can import the interfaces of common bots?
